services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo-db:27017/agency-command-center
    command: npm run dev
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
