name: Docker Build Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Docker Build
        # This builds your multi-stage Dockerfile to ensure no syntax errors or failing dependencies
        run: docker build -t agency-crm-backend .
